[[AWSCRT]]
arch = "aarch64"
git-tree-sha1 = "4800379bc7adb7f7dd052ee5ce2ab29ecbe23891"
os = "macos"

    [[AWSCRT.download]]
    sha256 = "a424c73675c04c94cf07a36aee44a4087b4fa7fb8621bfe974f7002a2cde77fe"
    url = "https://github.com/JuliaBinaryWrappers/AWSCRT_jll.jl/releases/download/AWSCRT-v0.1.1+0/AWSCRT.v0.1.1.aarch64-apple-darwin.tar.gz"
[[AWSCRT]]
arch = "aarch64"
git-tree-sha1 = "34f565f23e84748fde60be23525c700687853ad2"
libc = "glibc"
os = "linux"

    [[AWSCRT.download]]
    sha256 = "4007182eb47255fc80f6a0c2dfaf4e680e21658af1c7768c8be474ad8093528a"
    url = "https://github.com/JuliaBinaryWrappers/AWSCRT_jll.jl/releases/download/AWSCRT-v0.1.1+0/AWSCRT.v0.1.1.aarch64-linux-gnu.tar.gz"
[[AWSCRT]]
arch = "aarch64"
git-tree-sha1 = "4c03954930030f9e029323ae871bd3810570cc60"
libc = "musl"
os = "linux"

    [[AWSCRT.download]]
    sha256 = "3d042d238e2016591e295fdab5c542e410612e10190cbee448c700c70b1817a8"
    url = "https://github.com/JuliaBinaryWrappers/AWSCRT_jll.jl/releases/download/AWSCRT-v0.1.1+0/AWSCRT.v0.1.1.aarch64-linux-musl.tar.gz"
[[AWSCRT]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "ccfb82af5f637864f119ad91ae45e3923e08d3f0"
libc = "glibc"
os = "linux"

    [[AWSCRT.download]]
    sha256 = "8a7ffa65301d4e37c026e6df041866aecdf1ce84d49a3a2b0b84f07550e4aa27"
    url = "https://github.com/JuliaBinaryWrappers/AWSCRT_jll.jl/releases/download/AWSCRT-v0.1.1+0/AWSCRT.v0.1.1.armv6l-linux-gnueabihf.tar.gz"
[[AWSCRT]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "8494f94a24f02163fb87d347ce74de15cbfb83f4"
libc = "musl"
os = "linux"

    [[AWSCRT.download]]
    sha256 = "1dac5f57bacdf5527b5327ae2e62898a4182c29bdc066747666406654a0f96a6"
    url = "https://github.com/JuliaBinaryWrappers/AWSCRT_jll.jl/releases/download/AWSCRT-v0.1.1+0/AWSCRT.v0.1.1.armv6l-linux-musleabihf.tar.gz"
[[AWSCRT]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "00dfe2b73e11523655e792a54ab3221241994542"
libc = "glibc"
os = "linux"

    [[AWSCRT.download]]
    sha256 = "21115b9645e771a2398dc6f236e71247346be418d8b5faf34ce049c31b8ff4cf"
    url = "https://github.com/JuliaBinaryWrappers/AWSCRT_jll.jl/releases/download/AWSCRT-v0.1.1+0/AWSCRT.v0.1.1.armv7l-linux-gnueabihf.tar.gz"
[[AWSCRT]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "38fc1b3cbee498e2c58f2b1b0efbe21436e80da9"
libc = "musl"
os = "linux"

    [[AWSCRT.download]]
    sha256 = "20cb30fd060d0c53770f9f7444344400e1713af20f6876ab52dcb3a2eb4dbd92"
    url = "https://github.com/JuliaBinaryWrappers/AWSCRT_jll.jl/releases/download/AWSCRT-v0.1.1+0/AWSCRT.v0.1.1.armv7l-linux-musleabihf.tar.gz"
[[AWSCRT]]
arch = "i686"
git-tree-sha1 = "68a74e4c96fe4a7f7f88388e2911f1b7fddade53"
libc = "glibc"
os = "linux"

    [[AWSCRT.download]]
    sha256 = "b9ccde64c65c4eee6e38bf317bcd4ad0526308e45e02fe9d67ec002c03d47650"
    url = "https://github.com/JuliaBinaryWrappers/AWSCRT_jll.jl/releases/download/AWSCRT-v0.1.1+0/AWSCRT.v0.1.1.i686-linux-gnu.tar.gz"
[[AWSCRT]]
arch = "i686"
git-tree-sha1 = "0e459a7f41f13fc4a22a423fe692a94f4ead86fa"
libc = "musl"
os = "linux"

    [[AWSCRT.download]]
    sha256 = "65639b558d0f2acb9911607da5e33e40e33f18c7eb7d69e3bb6561f372eb9ed8"
    url = "https://github.com/JuliaBinaryWrappers/AWSCRT_jll.jl/releases/download/AWSCRT-v0.1.1+0/AWSCRT.v0.1.1.i686-linux-musl.tar.gz"
[[AWSCRT]]
arch = "powerpc64le"
git-tree-sha1 = "fcf19f7d9866601eb3be54f7483243270b615b3e"
libc = "glibc"
os = "linux"

    [[AWSCRT.download]]
    sha256 = "d83b138a1861f1048c9a3f07612dd7bf3f6125e0013a35d1a542d88b898d19c9"
    url = "https://github.com/JuliaBinaryWrappers/AWSCRT_jll.jl/releases/download/AWSCRT-v0.1.1+0/AWSCRT.v0.1.1.powerpc64le-linux-gnu.tar.gz"
[[AWSCRT]]
arch = "x86_64"
git-tree-sha1 = "beefe6d63b0cb7f63e5fd56dc26f7cb7fbe654ea"
os = "macos"

    [[AWSCRT.download]]
    sha256 = "95fb961e2f52e7d1f40c7669512dc1c527a473baa40213e4581a9684302ef9c8"
    url = "https://github.com/JuliaBinaryWrappers/AWSCRT_jll.jl/releases/download/AWSCRT-v0.1.1+0/AWSCRT.v0.1.1.x86_64-apple-darwin.tar.gz"
[[AWSCRT]]
arch = "x86_64"
git-tree-sha1 = "92d49a7c9ad8f335cef3f3863856a100fdb18f04"
libc = "glibc"
os = "linux"

    [[AWSCRT.download]]
    sha256 = "d07b6e4bfc90695f19adda4d73b600507a67a5f628c597f591441de9ff7bd9da"
    url = "https://github.com/JuliaBinaryWrappers/AWSCRT_jll.jl/releases/download/AWSCRT-v0.1.1+0/AWSCRT.v0.1.1.x86_64-linux-gnu.tar.gz"
[[AWSCRT]]
arch = "x86_64"
git-tree-sha1 = "aa888ac8c3ed203598af3a64e031a313de7e9846"
libc = "musl"
os = "linux"

    [[AWSCRT.download]]
    sha256 = "26ee66739bdafd04af45cfe3b3bc06707a6ec3891fe77c8d02b6a8025dde454a"
    url = "https://github.com/JuliaBinaryWrappers/AWSCRT_jll.jl/releases/download/AWSCRT-v0.1.1+0/AWSCRT.v0.1.1.x86_64-linux-musl.tar.gz"
