# Autogenerated wrapper script for AWSCRT_jll for powerpc64le-linux-gnu
export libawscrt

using aws_c_auth_jll
using aws_c_cal_jll
using aws_c_event_stream_jll
using aws_c_http_jll
using aws_c_iot_jll
using aws_c_mqtt_jll
using aws_c_s3_jll
using aws_checksums_jll
JLLWrappers.@generate_wrapper_header("AWSCRT")
JLLWrappers.@declare_library_product(libawscrt, "libawscrt.so")
function __init__()
    JLLWrappers.@generate_init_header(aws_c_auth_jll, aws_c_cal_jll, aws_c_event_stream_jll, aws_c_http_jll, aws_c_iot_jll, aws_c_mqtt_jll, aws_c_s3_jll, aws_checksums_jll)
    JLLWrappers.@init_library_product(
        libawscrt,
        "lib/libawscrt.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
