# Autogenerated wrapper script for AWSCRT_jll for x86_64-apple-darwin
export libawscrt

JLLWrappers.@generate_wrapper_header("AWSCRT")
JLLWrappers.@declare_library_product(libawscrt, "@rpath/libawscrt.dylib")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libawscrt,
        "lib/libawscrt.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
